# Generated by Django 5.2.11 on 2026-03-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='external_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
