# Generated by Django 5.2.10 on 2026-02-01 19:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from decimal import Decimal

import api.assessment.models


def forwards_func(apps, schema_editor):
    MediaCategory = apps.get_model('assessment', 'MediaCategory')

    media_categories = [
        MediaCategory(code='movie', name='Movie'),
        MediaCategory(code='serial', name='Serial'),
        MediaCategory(code='anime', name='Anime'),
        MediaCategory(code='game', name='Game'),
        MediaCategory(code='book', name='Book'),
        MediaCategory(code='song', name='Song'),
        MediaCategory(code='video', name='Video'),
    ]
    MediaCategory.objects.bulk_create(media_categories)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                (
                    'code',
                    models.CharField(
                        choices=[
                            ('movie', 'Movie'),
                            ('serial', 'Serial'),
                            ('anime', 'Anime'),
                            ('game', 'Game'),
                            ('book', 'Book'),
                            ('song', 'Song'),
                            ('video', 'Video'),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                (
                    'assessment_status',
                    models.CharField(
                        choices=[('initial', 'Initial'), ('in_progress', 'In Progress'), ('completed', 'Completed')],
                        default='initial',
                    ),
                ),
                ('assessment_until_dt', models.DateTimeField(blank=True, null=True)),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='media', to='assessment.mediacategory'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'mark',
                    models.DecimalField(
                        decimal_places=1,
                        help_text='Your mark, from 1 to 10 in half steps.',
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('1')),
                            django.core.validators.MaxValueValidator(Decimal('10')),
                            api.assessment.models.validate_half_step,
                        ],
                    ),
                ),
                (
                    'partial',
                    models.CharField(
                        blank=True,
                        help_text='Indicates that the media has been partially reviewed, for example, 5 / 10 episodes of an anime.',
                        max_length=300,
                    ),
                ),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='assessments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'media',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessment.media'
                    ),
                ),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('media', 'user'), name='uq_assessment_media_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='uq_media_name_currency'),
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
