# Generated by Django 5.2.10 on 2026-02-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, help_text='Description for quick media memorization.'),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(help_text='URL that describes the media, such as an IMDb page.'),
        ),
    ]
