# Generated by Django 5.2.10 on 2026-02-13 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, _schema_editor):
    Media = apps.get_model('assessment', 'Media')
    User = apps.get_model('user', 'User')

    admin = User.objects.get(username='admin')
    Media.objects.update(creator_id=admin.id)


class Migration(migrations.Migration):
    dependencies = [
        ('assessment', '0002_alter_media_description_alter_media_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='creator',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='media',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='media',
            name='creator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='media', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
