# Generated by Django 5.2.11 on 2026-02-14 15:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assessment', '0003_media_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                (
                    'status',
                    models.CharField(choices=[('initial', 'Initial'), ('completed', 'Completed')], default='initial'),
                ),
                ('candidates', models.ManyToManyField(related_name='polls', to='assessment.media')),
                (
                    'winner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='winning_polls',
                        to='assessment.media',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'ranks',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BigIntegerField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    'poll',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='assessment.poll'
                    ),
                ),
                (
                    'voter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='votes', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='voters',
            field=models.ManyToManyField(
                related_name='polls',
                through='assessment.Vote',
                through_fields=('poll', 'voter'),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
