# Generated by Django 5.2.11 on 2026-03-15 11:34

import django.core.validators
from django.db import migrations, models

from decimal import Decimal

import api.assessment.models


class Migration(migrations.Migration):
    dependencies = [
        ('assessment', '0004_poll_vote_poll_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='mark',
            field=models.DecimalField(
                decimal_places=1,
                help_text='Your mark, from 0 to 10 in half steps.',
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0')),
                    django.core.validators.MaxValueValidator(Decimal('10')),
                    api.assessment.models.validate_half_step,
                ],
            ),
        ),
    ]
