# Generated by Django 5.2.11 on 2026-03-29 11:49

import django.core.validators
from django.db import migrations, models

from decimal import Decimal


class Migration(migrations.Migration):
    dependencies = [
        ('assessment', '0005_alter_assessment_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='meta_mark',
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal('0')),
                    django.core.validators.MaxValueValidator(Decimal('10')),
                ],
            ),
        ),
    ]
