name: Wake up bot by cron job

on:
  schedule:
    - cron: '*/8 * * * *'

jobs:
  test:
    name: Run wake-up request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.11"
          cache: "pipenv"

      - name: Install pipenv and dependencies
        run: |
          pip install --no-cache-dir pipenv==2026.0.3
          pipenv sync --dev

      - name: Run wake-up request
        env:
          APP_EXTERNAL_URL: ${{ secrets.APP_EXTERNAL_URL }}
        run: pipenv run wake-up-bot
