name: CI/CD

on:
  push:
    branches: ["dev"]

permissions:
  contents: read
  actions: read
  deployments: write

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18.1-alpine
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: app
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -h 127.0.0.1 -U app -d app"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13.12"
          cache: "pipenv"

      - name: Install pipenv and dependencies
        run: |
          pip install --no-cache-dir pipenv==2026.5.1
          pipenv sync --dev

      - name: Run tests
        env:
          APP_DB_URL: postgres://app:app@localhost:5432/app
        run: pipenv run test

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy
        uses: JorgeLNJunior/render-deploy@v1.5.0
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          github_deployment: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deployment_environment: "dev"
